Models/DanieStatystykiViewModel.cs
namespace MvcRestauracja.Models
{
    public class DanieStatystykiViewModel
    {
        public string NazwaDania { get; set; }
        public int LiczbaZamowien { get; set; }
    }
}

Models/Klient.cs
using System.ComponentModel.DataAnnotations;

namespace MvcRestauracja.Models
{
    public class Klient
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Imię")]
        public String Imie { get; set; }
        [Display(Name = "Nazwisko")]
        public String Nazwisko { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data zamowienia")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DataZamowienia { get; set; }
        public ICollection<Danie> ?Dania { get; set; } = new List<Danie>();
        public Stolik? Stolik { get; set; }

  

    }
}

Controllers/KlientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcRestauracja.Data;
using MvcRestauracja.Models;

namespace MvcRestauracja.Controllers
{
    public class KlientController : Controller
    {
        private readonly MvcRestauracjaContext _context;

        public KlientController(MvcRestauracjaContext context)
        {
            _context = context;
        }

        // GET: Klient
        public async Task<IActionResult> Index()
        {
            var klient = _context.Klient.Include(p => p.Stolik).Include(p => p.Dania).AsNoTracking();
            return View(await klient.ToListAsync());
        }

        // GET: Klient/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klient = await _context.Klient
                .Include(p => p.Stolik)
                .Include(p => p.Dania)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (klient == null)
            {
                return NotFound();
            }


            return View(klient);
        }
        private void PopulateDaniaDropDownList(object selectedDania = null)
        {
            IEnumerable<int> selectedDaniaId = null;
            if (Request.HasFormContentType)
            {
                selectedDaniaId = Request.Form["Dania"].ToString().Split(',').Select(int.Parse);
            }
            else if (selectedDania != null && selectedDaniaId is IEnumerable<int>)
            {
                selectedDaniaId = selectedDania as IEnumerable<int>;
            }
            ViewBag.DaniaID = new MultiSelectList(_context.Dania, "Id", "Nazwa", selectedDaniaId);
        }

        private void PopulateStolikDropDownList(int? selectedStolik = null)
        {
            var wybranyStolik = from e in _context.Stolik
                                orderby e.Nazwa
                                select e;
            var res = wybranyStolik.AsNoTracking();
            ViewBag.StolikID = new SelectList(res, "Id", "Nazwa", selectedStolik);
        }

        public async Task<IActionResult> DanieStatystyki()
        {
            // Pobranie wszystkich klientów z ich zamówieniami
            var klienci = await _context.Klient.Include(k => k.Dania).ToListAsync();

            // Zliczenie liczby zamówień dla każdego dania
            var zamowioneDania = klienci
                .SelectMany(k => k.Dania)
                .GroupBy(d => d.Nazwa)
                .Select(g => new DanieStatystykiViewModel
                {
                    NazwaDania = g.Key,
                    LiczbaZamowien = klienci.Count()
                })
                .ToList();

            return View("DanieStatystyki", zamowioneDania);
        }







        // GET: Klient/Create
        public IActionResult Create()
        {
            PopulateDaniaDropDownList();
            PopulateStolikDropDownList();
            return View();
        }
        // POST: Klient/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("Id,Imie,Nazwisko,DataZamowienia")] Klient klient, IFormCollection form)
        {
            string stolikValue = form["Stolik"].ToString();
            if (ModelState.IsValid)
            {
                var selectedDania = new List<int>();

                if (!string.IsNullOrEmpty(form["Dania"]))
                {
                    selectedDania = form["Dania"].ToString().Split(',')
                                    .Where(s => int.TryParse(s, out _))
                                    .Select(int.Parse)
                                    .ToList();
                }
                klient.Dania = _context.Dania.Where(s => selectedDania.Contains(s.Id)).ToList();

                Stolik stolik = null;
                if (stolikValue != "-1")
                {
                    var ee = _context.Stolik.Where(e => e.Id == int.Parse(stolikValue));

                }
                klient.Stolik = stolik;
                _context.Add(klient);
                await _context.SaveChangesAsync();

                // Aktualizujemy statystyki dania i przekazujemy do widoku
                return await DanieStatystyki();

                // return View("DanieStatystyki", statystykiDania); // Tutaj przekazujemy do widoku statystyki dania
            }
            PopulateStolikDropDownList();
            return View(klient);
        }


        // GET: Klient/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klient = _context.Klient.Where(p => p.Id == id)
                    .Include(p => p.Stolik).Include(p => p.Dania).First();
            if (klient == null)
            {
                return NotFound();
            }
            PopulateStolikDropDownList(klient.Stolik?.Id);

            PopulateDaniaDropDownList(klient.Dania.Select(s => s.Id));
            return View(klient);
        }

        // POST: Klient/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Klient/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Imie,Nazwisko,DataZamowienia")] Klient klient, IFormCollection form)
        {
            if (id != klient.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    String stolikValue = form["Stolik"];
                    Stolik stolik = null;
                    if (!string.IsNullOrEmpty(stolikValue) && stolikValue != "-1")
                    {
                        var ee = _context.Stolik.Where(e => e.Id == int.Parse(stolikValue));
                        if (ee.Count() > 0)
                            stolik = ee.First();
                    }

                    var selectedDania = form["Dania"].ToString().Split(',').Select(int.Parse).ToList();
                    klient.Dania = _context.Dania.Where(s => selectedDania.Contains(s.Id)).ToList();
                    klient.Stolik = stolik;
                    _context.Update(klient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KlientExists(klient.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(klient);
        }


        // GET: Klient/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Klient == null)
            {
                return NotFound();
            }

            var klient = await _context.Klient
                .Include(p => p.Stolik)
                .Include(p => p.Dania)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (klient == null)
            {
                return NotFound();
            }

            return View(klient);
        }

        // POST: Klient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var klient = await _context.Klient
                    .Include(k => k.Dania) // Uwzględnij powiązane dania
                    .FirstOrDefaultAsync(k => k.Id == id);

                if (klient == null)
                {
                    return NotFound();
                }

                // Usuń powiązane dania
                if (klient.Dania != null)
                {
                    klient.Dania.Clear();
                }

                _context.Klient.Remove(klient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return Problem($"An error occurred while deleting the client: {ex.Message}");
            }
        }



        private bool KlientExists(int id)
        {
            return (_context.Klient?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Klient/Create.cshtml
@model MvcRestauracja.Models.Klient

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Imie" class="control-label"></label>
        <input asp-for="Imie" class="form-control" />
        <span asp-validation-for="Imie" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Nazwisko" class="control-label"></label>
        <input asp-for="Nazwisko" class="form-control" />
        <span asp-validation-for="Nazwisko" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DataZamowienia" class="control-label"></label>
        <input asp-for="DataZamowienia" class="form-control" />
        <span asp-validation-for="DataZamowienia" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Stolik.Id" class="control-label"></label>
        <select asp-for="Stolik.Id" class="form-control" asp-items="ViewBag.StolikID"></select>
    </div>
    <div class="form-group">
        <label asp-for="Dania" class="control-label"></label>
        <select asp-for="Dania" class="form-control" asp-items="ViewBag.DaniaID" multiple></select>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

Views/Klient/DanieStatystyki.cshtml
@model List<MvcRestauracja.Models.DanieStatystykiViewModel>

@{
    ViewData["Title"] = "Statystyki dań";
}

<div class="container">
    <h1>Statystyki dań</h1>

    <div class="row">
        <div class="col">
            <a class="btn btn-secondary" asp-action="Dashboard" asp-controller="Home">Powrót do panelu</a>
        </div>
        <div class="col text-right">
            <a class="btn btn-secondary" asp-action="Index" asp-controller="Klient">Powrót</a>
        </div>
    </div>

    <hr />

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nazwa dania</th>
                <th>Liczba zamówień</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.NazwaDania</td>
                    <td>@item.LiczbaZamowien</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Klient/Delete.cshtml
@model MvcRestauracja.Models.Klient

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Klient</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZamowienia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZamowienia)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Powrót do listy</a>
    </form>
</div>

Views/Klient/Details.cshtml
@model MvcRestauracja.Models.Klient

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Klient</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZamowienia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZamowienia)
        </dd>
    </dl>
</div>
 <div class="row mt-3">
        <div class="col-md-6">
            <form asp-action="Delete" method="post">
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edytuj</a>
                <a asp-action="Index" class="btn btn-secondary">Powrót do listy</a>
            </form>
        </div>
    </div>

Views/Klient/Edit.cshtml
@model MvcRestauracja.Models.Klient

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="Imie" class="control-label"></label>
        <input asp-for="Imie" class="form-control" />
        <span asp-validation-for="Imie" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Nazwisko" class="control-label"></label>
        <input asp-for="Nazwisko" class="form-control" />
        <span asp-validation-for="Nazwisko" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DataZamowienia" class="control-label"></label>
        <input asp-for="DataZamowienia" class="form-control" />
        <span asp-validation-for="DataZamowienia" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Stolik.Id" class="control-label"></label>
        <select asp-for="Stolik.Id" class="form-control" asp-items="ViewBag.StolikID"></select>
    </div>
    <div class="form-group">
        <label asp-for="Dania" class="control-label"></label>
        <select asp-for="Dania" class="form-control" asp-items="ViewBag.DaniaID" multiple></select>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-secondary">Powrót do listy</a>
    </div>
</form>

Views/Klient/Index.cshtml
@model IEnumerable<MvcRestauracja.Models.Klient>

@{
    ViewData["Title"] = "Klienci";
}

<div class="container">
    <h1>Klienci</h1>

    <div class="row">
        <div class="col">
            <a class="btn btn-primary" asp-action="Create">Dodaj nowego klienta</a>
        </div>
        <div class="col text-middle">
            <a class="btn btn-secondary" asp-action="Dashboard" asp-controller="Home">Powrót do panelu</a>
        </div>
        <div class="col text-right">
            <a class="btn btn-secondary" asp-action="DanieStatystyki" asp-controller="Klient">Statystyki Dań</a>
        </div>
    </div>

    <hr />

    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Imie)</th>
                <th>@Html.DisplayNameFor(model => model.Nazwisko)</th>
                <th>@Html.DisplayNameFor(model => model.DataZamowienia)</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Imie)</td>
                    <td>@Html.DisplayFor(modelItem => item.Nazwisko)</td>
                    <td>@Html.DisplayFor(modelItem => item.DataZamowienia)</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edytuj</a>
                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Szczegóły</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>